name: Deploy My Portfolio

on:
  push:
    branches: 
      - master

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  deploy:
    needs: build_site
    runs-on: ubuntu-latest
    env:
      BASE_PATH: ''  # Set the base path to root

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      - name: Deploy
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          keep_files: false
          commit_message: "Deploy Site"
          publish_dir: ./build
          target_branch: gh-pages
          clean: true
